### PR TITLE
Initial Version based on STM32 CPU-Support Package from Rowley in Version Version 3.49 (2023-10-02)

### PR DESCRIPTION
**Pull request by Masmiseim36**
Maybe it helps as a starting point for creating your own CPU-Support Packages. This showns how the original STM32 CPU-Package can be created

### CODE REVIEW

**Comment by mymy49** [comment]
> Maybe it helps as a starting point for creating your own CPU-Support Packages. This showns how the original STM32 CPU-Package can be created

Thank you very much!!

When I download the STM32_V3-3.49.hzq file and unpacked it using mkpkg, I was confused because there was no hzp file. I'm not good at English, but I was planning to give it a try after reading some of the documentation.

But Based on what you shared, I can be able to do something right away. thank you ^^

**Comment by Masmiseim36** [comment]
The hzp file is not part of the package, so you have to create it yourself

**Comment by mymy49** [comment]
Currently, registration as STM32_Custom is successful and compilation and debugging work well. Thank you!!

So I thought about what the next step would be. I analyze the code in detail for STM32? Or I analyze the detailed code while registering the MCU I want to use? 

In conclusion, I will try to register the MCU I want. I am planning to create a new related repository. Once I get the target board, I will create a repository.

**Comment by Masmiseim36** [comment]
As I had already written in the Rowley forum, try to understand the Various XML files which must be available in the package.
•	Package Description --> What is in the package
•	Project Template --> Initial structure for new projects
•	Property Groups --> additional Options which can be changed, like controller variants, or target memory.
•	Memory Map --> Basically, where is RAM and Flash located
You can find the documentation for the files here: https://www.rowleydownload.co.uk/arm/documentation/file_formats.htm

The target script (JavaScript) file is also important. This describes how a connection to the controller is to be established. Some JTAG adapters such as those from Segger have their own intelligence, in which case it is sufficient to use the correct controller name. Others, such as the CMSIS adapters or the CrossConnect from Rowley, do not have their own intelligence. In this case, it is likely that additional instructions will need to be implemented. Unfortunately, the documentation here is not so good, so it is best to look at what is done in the scripts for other controllers.

Such a script can become quite extensive. Compare, for example, my script for the iMXRT family:
https://github.com/Masmiseim36/iMXRT/blob/master/targets/iMXRT/iMXRT_Target.js

**Comment by mymy49** [comment]
All right. thank you.

Let's take a closer look at the information you provided in the process of selecting a target and adding that target.

I left a question about JTAG Adapter in the link below. Once this is resolved, I plan to purchase a target board.
[https://rowley.zendesk.com/hc/en-us/community/posts/16815059425053-This-is-a-question-related-to-JTAG-Adapter](https://rowley.zendesk.com/hc/en-us/community/posts/16815059425053-This-is-a-question-related-to-JTAG-Adapter)

**Comment by Masmiseim36** [comment]
Do you have the schematics of the Board?
You can use other JTAG adapters as long as the JTAG Interface is available on some pins. Which one would you prefere?

**Comment by mymy49** [comment]
The MCU under consideration is the A34M420YL. It has both a JTAG pin and a SWD pin. Can I use this MCU with J-LINK or Crossconnect?

[UM_A34M41x_Eng.pdf](https://github.com/mymy49/CrossworksForARM_STM32F103VC_Package_Test/files/14326075/UM_A34M41x_Eng.pdf)

**Comment by Masmiseim36** [comment]
All ARM CPUs (at least the one I'm aware of) use the ARM-Coresight-Implementation as a JTAG/SWD interface. So basically CMSIS-DAP, CrossConnect or J-Link should work. However, sometimes controller vendors do some strange things inside the chip, so that you need to play with the settings in the target-script file. If you read through some of the script files for different controller, you get an idea.
However, Segger has direct support for Abov (https://www.segger.com/supported-devices/abov/). So Segger should work without any problems. CMSIS-DAP and CrossConnect may also work without an issue, but it is more likely that you need to do some configuration here.
In addition, you need to check if your Evaluation Boards supports external JTAG-Adapters. All the required Signals needs to be on a JTAG-pin header. You also need to ensure that the onboard JTAG is disabled when using an external one.

**Comment by mymy49** [comment]
Board-related documents are not publicly available on the website, so exact confirmation is not possible. Since the MCU is valid for both JTAG and SWD, it seems that it will be possible to simply create and use a separate adapter board.

So, I will proceed with purchasing the board.

**Comment by mymy49** [comment]
I contacted ABOV for a board, but didn't hear back, so I ordered a WIZnet product.
[https://www.wiznet.io/product-item/wizwiki-w7500/](https://www.wiznet.io/product-item/wizwiki-w7500/)

I am currently creating a repository and registering W7500.
[https://github.com/mymy49/CrossworksForARM_WIZnet](https://github.com/mymy49/CrossworksForARM_WIZnet)

A problem occurred during work. The contents of Peripheral.xml do not apply. If you create a project with a target MCU and debug it with "ARM simulator", the register list does not appear.

What mistake did I make?

**Comment by mymy49** [comment]
After looking around, I found the KinetisSimulatorMemory file.

It seems to be a file that supports the simulator, but even if I open the related hzp file, the project ends with an error saying that the DLL file is missing. What should I refer to in this part?

**Comment by Masmiseim36** [comment]
Your Package seems to work on my PC. I can see the register during debugging with the Simulator.
grafik
Unfortunately, WizNet does not seem to provide a register description file. At NXP these are part of the SDK.

Unfortunately, I have no experience with the DLLS of the simulator.

**Comment by mymy49** [comment]
After seeing your reply, I also tried it on another PC. it worked fine!!

I wonder why that happened on the PC I was working on... I should try deleting temporary files and cache-related files.

I hope the board arrives quickly so I can attach SWD!

Thank you very much~!

**Comment by mymy49** [comment]
I found the reason why the register is not updated.

In the code below, the 'build_version' item must be modified to update the register item.
[https://github.com/mymy49/CrossworksForARM_WIZnet/blob/main/packages/WIZnet_package.xml#L2](https://github.com/mymy49/CrossworksForARM_WIZnet/blob/main/packages/WIZnet_package.xml#L2)

**Comment by mymy49** [comment]
I currently have the target board operating normally through debugging with J-LINK.

I am trying to debug using CMSIS-DAP. At this stage, I have inquired with the manufacturer about where to obtain the MCU ID. I am writing registers for peripheral devices while waiting for a reply.

I have one question about this. How should the register be defined when it is 64 bits? I tried to look for it in the existing code, but I couldn't find it.

Thank you very much.

**Comment by mymy49** [comment]
I copied most of your readme. If you are offended, I will delete it and write a new one.

[https://github.com/mymy49/CrossworksForARM_WIZnet](https://github.com/mymy49/CrossworksForARM_WIZnet)

**Comment by Masmiseim36** [comment]
thats fine

**Comment by Masmiseim36** [comment]
> I currently have the target board operating normally through debugging with J-LINK.
> 
> I am trying to debug using CMSIS-DAP. At this stage, I have inquired with the manufacturer about where to obtain the MCU ID. I am writing registers for peripheral devices while waiting for a reply.
> 
> I have one question about this. How should the register be defined when it is 64 bits? I tried to look for it in the existing code, but I couldn't find it.
> 
> Thank you very much.

You were able to debug with your CPU support package in Crossworks with a J-Link adapter on the Wiznet board. That's already a good result :-)


If you use the OnBoard CMSIS-DAP adapter instead of the J-Link adapter, does it not work? What exactly happens when you connect to the board via CMSIS-DAP?


Regarding the register description. There is a standard from ARM that specifies what a register description file should look like (https://www.keil.com/pack/doc/CMSIS/Core/html/device_h_pg.html).

For debuggers, this should be made available in XML format (https://www.keil.com/pack/doc/CMSIS/SVD/html/schema_1_2_gr.html). There is also a converter that generates a header file from the XML file. However, I have not yet used this (https://arm-software.github.io/CMSIS_5/SVD/html/svd_SVDConv_pg.html).

**Comment by mymy49** [comment]
**You were able to debug with your CPU support package in Crossworks with a J-Link adapter on the Wiznet board. That's already a good result :-)**
you're right. I am very happy to have been able to use this product with my own hands in Crossworks for ARM. Still, since CMSIS-DAP is installed on the board, I have a desire to use it.

**If you use the OnBoard CMSIS-DAP adapter instead of the J-Link adapter, does it not work? What exactly happens when you connect to the board via CMSIS-DAP?**
The code below runs without problem. However, it does not check by reading the actual MCU ID, but proceeds by unconditionally returning true.
[https://github.com/mymy49/CrossworksForARM_WIZnet/blob/main/targets/WIZnet/W7500x/W7500_Target.js#L105](https://github.com/mymy49/CrossworksForARM_WIZnet/blob/main/targets/WIZnet/W7500x/W7500_Target.js#L105)

The process of erasing the flash or downloading the program will proceed. However, it is not actually erased and cannot be downloaded. Crossworks shows a warning that the contents of the flash are different from the original. And the debugging screen appears. My guess is, I'll have to write a Flash Loader?

**Regarding the register description. There is a standard from ARM that specifies what a register description file should look like (https://www.keil.com/pack/doc/CMSIS/Core/html/device_h_pg.html).**

**For debuggers, this should be made available in XML format (https://www.keil.com/pack/doc/CMSIS/SVD/html/schema_1_2_gr.html). There is also a converter that generates a header file from the XML file. However, I have not yet used this (https://arm-software.github.io/CMSIS_5/SVD/html/svd_SVDConv_pg.html).**
It seems too difficult to me now. ^^; I don't even know where to use this right now. I'll probably remember the link you gave me naturally when I need it.

Thank you very much~!

**Comment by Masmiseim36** [comment]
To read the MCU ID, the controller must provide a corresponding register. Not every controller has such a register. Kinetis controllers from NXP offer such a register (SIM->SDIO), but iMXRT, also from NXP, does not.

If such a register is available, it can be read out with TargetInterface.peekUint32().


To write to the flash, a flash loader must be written. This is a small application that is executed from the RAM and accepts commands and data via JTAG in order to write to the flash. Crossworks offers the library "Libmem Loader" (-->https://www.rowleydownload.co.uk/arm/documentation/index.htm), in which the communication with the debugger is implemented via JTAG and defines callbacks for the read and write routines on the flash.

The loader must then be integrated into the CPU support package. The arm_target_flash_loader_file_path option must be set in the project template for this purpose.

Regards

**Comment by mymy49** [comment]
[https://github.com/Masmiseim36/iMXRT/blob/master/targets/iMXRT/iMXRT_Target.js#L206](https://github.com/Masmiseim36/iMXRT/blob/master/targets/iMXRT/iMXRT_Target.js#L206)

It feels like it only passes by comparing the part names set in the project. I will also have to use this code. ^^

I am currently trying to learn how to erase and use the flash of the W7500 using J-LINK. Then let's work on the flash loader again. 

Thank you very much~!

**Comment by mymy49** [comment]
hello. You've been well, right

I am updating the Package by adding W7500 devices one by one. I am currently writing code for DMA. I didn't understand the content from the document alone. I contacted the manufacturer of the W7500 about a week ago, but there has been no response yet, so I'm waiting.

Do you mind if I ask you a question about ARM PrimeCell uDMA Controller(PL230)?

**Comment by Masmiseim36** [comment]
Hello @mymy49 ,


I'm afraid I don't have any experience with the PL230 DMA controller myself and probably won't be able to help you there.
But feel free to ask.

regards

**Comment by mymy49** [comment]
Thank you very much~!

I attempted to do this by referring to the source code in the link below.

https://github.com/Wiznet/W7500/blob/master/W7500x_Library_Examples/Libraries/W7500x_stdPeriph_Driver/src/W7500x_dma.c#L125

And from ARM's documentation, it appears to be related to the content in the link below.

https://developer.arm.com/documentation/ddi0417/a/Functional-Overview/Functional-operation/AHB-master-interface

However, it seems to be lacking in content. Is there a place where I can get additional information? I can't find any suitable information when I search. ㅠ.ㅠ

Best regards

**Comment by Masmiseim36** [comment]
Hello @mymy49,

You could try to ask in the ARM coummunity forum: https://community.arm.com/community-help/f/community-help-forum
You could also check if any other controller vendor is using this IP anch check if they provide driver for it.'

Regards

**Comment by mymy49** [comment]
Hello @Masmiseim36 ,

Thank you for looking~! I will try the method you recommended.

Thank you very much~!!

Best regards

**Comment by mymy49** [comment]
Hello @Masmiseim36 ,

I think I found an MCU that uses PL230. Nuvoton products seem to use PL230.

But... I really like the new MA35H0 series from Nuvoton these days. So I ordered the board and received it a few days ago. Since it doesn't seem to support J-LINK yet, I'm planning to work on it using CrossConnect Neo.

I opened a git repository as shown in the link below. ^^
[https://github.com/mymy49/CrossworksForARM_MA35H0](https://github.com/mymy49/CrossworksForARM_MA35H0)

Once this is completed, I plan to resume work on W7500 package support ^^;

**Comment by mymy49** [comment]
Hello @Masmiseim36 sir,

I have the same problem as the link below. Could you please help?
[https://rowley.zendesk.com/hc/en-us/community/posts/19134884314269-MA35H0-Cannot-find-debug-component-in-ROM-Table](https://rowley.zendesk.com/hc/en-us/community/posts/19134884314269-MA35H0-Cannot-find-debug-component-in-ROM-Table)

When asking a question, would it be better to ask it personally? Or would it be better to ask the question in a public place?

Best regards,
Yoon-Ki Hong

**Comment by Masmiseim36** [comment]
Hello,

Using a DualCore A35 as BareMetal is a bit unusual, Linux is usually used here. Have you tried to connect to the processor with the J-Link Commander via J-Link. Use a Gernic A35-Core. What output do you get there?
Have you used the “Explore” functionality in Crossworks with the Neo? You can find this by right-clicking on the CrossConnect in the target view.
Nuvuton uses their own JTAG adapter Nu-Link. This appears to be a CMSIS-DAP adapter (so should also work with Crossworks). If you install Nuvuton's own development environment NuEclipse, you will find the configuration for the Nu-Link under 
```
.\OpenOCD\scripts\target\numicroMA35H0.cfg. 
```
There you can possibly get a few suggestions for the Crossworks Taregt script. For example, try the following in the target script:
```JavaScript
function Connect ()
{
    TargetInterface.setDebugInterfaceProperty ("set_adiv5_APB_ap_num", 1);
    TargetInterface.setDebugInterfaceProperty ("component_base",  0xE0C10000);
}

```

Regards

**Comment by mymy49** [comment]
Hello @Masmiseim36 sir,

I got a lot of hints! I'll try them one by one and let you know the results.

Thank you very much!!


Best Regards,

Yoon-Ki Hong

**Comment by mymy49** [comment]
The output below is the result of J-Link Commander.

```
J-Link>connect
Please specify device / core. <Default>: CORTEX-A35
Type '?' for selection dialog
Device>CORTEX-A35
Please specify target interface:
  J) JTAG (Default)
  S) SWD
  T) cJTAG
TIF>J
Device position in JTAG chain (IRPre,DRPre) <Default>: -1,-1 => Auto-detect
JTAGConf>
Specify target interface speed [kHz]. <Default>: 4000 kHz
Speed>
Device "CORTEX-A35" selected.



Connecting to target via JTAG
TotalIRLen = 4, IRPrint = 0x01
JTAG chain detection found 1 devices:
 #0 Id: 0x6BA00477, IRLen: 04, CoreSight JTAG-DP
DPv0 detected
Scanning AP map to find all available APs
AP[3]: Stopped AP scan as end of AP map has been reached
AP[0]: AXI-AP (IDR: 0x44770004)
AP[1]: APB-AP (IDR: 0x54770002)
AP[2]: AHB-AP (IDR: 0x24770011)
Iterating through AP map to find APB-AP to use
AP[0]: Skipped. Not an APB-AP
AP[1]: APB-AP found
No AP map specified by user. Setting auto-detected AP map.
Core base address and CTI core base address are both not set. Performing autodetection as fallback.
Scanning ROMTbl @ 0xE0800000
[0]Comp[0] @ 0xE0801000: CTI (?)
[0]Comp[1] @ 0xE0802000: TSG
[0]Comp[2] @ 0xE0803000: ATBR (?)
[0]Comp[3] @ 0xE0804000: TPIU
[0]Comp[4] @ 0xE0805000: ETB
[0]Comp[5] @ 0xE0806000: CSTF
[0]Comp[6] @ 0xE0C00000: ROM Table
Scanning ROMTbl @ 0xE0C00000
[1]Comp[0] @ 0xE0C10000: Cortex-A35
[1]Comp[1] @ 0xE0C20000: CSS600-CTI
Core found. Stopped ROM table scan: https://wiki.segger.com/ROMTableScan
Cortex-A35 @ 0xE0C10000 (detected)
CoreCTI @ 0xE0C20000 (detected)
Debug architecture: ARMv8.0
6 code breakpoints, 4 data breakpoints
Processor features:
  EL0 support: AArch64 + AArch32
  EL1 support: AArch64 + AArch32
  EL2 support: AArch64 + AArch32
  EL3 support: AArch64 + AArch32
  FPU support: Single + Double + Conversion
Add. info (CPU temp. halted)
CPU could not be halted
Failed to temporarily halt CPU
Connect failed. Resetting via Reset pin and trying again.
TotalIRLen = 4, IRPrint = 0x01
JTAG chain detection found 1 devices:
 #0 Id: 0x6BA00477, IRLen: 04, CoreSight JTAG-DP
DPv0 detected
Scanning AP map to find all available APs
AP[0]: Stopped AP scan as end of AP map seems to be reached
Iterating through AP map to find APB-AP to use

****** Error: Specific core setup failed.
Could not find matching AP (APB-AP) in CoreSight setup. Debugging not possible.
Could not determine APB-AP (debugging not possible)
Error occurred: Could not connect to the target device.
For troubleshooting steps visit: https://wiki.segger.com/J-Link_Troubleshooting

```

**Comment by mymy49** [comment]
The explorer function did not detect the CPU.

스크린샷 2024-06-01 11-15-16

**Comment by mymy49** [comment]
NuEclipse installation failed. The operating system of my PC is Ubuntu 24.04, but the recommended OS for NuEclipse seems to be Ubuntu 18.04.

**Comment by mymy49** [comment]
I understand that Nu-Link2-Pro supports MA35 series. I plan to order the product in about 15 days. After ordering, I will test it and let you know the results.

Thank you very much~!

Best Regards,
Yoon-Ki Hong

**Pull request merged**
